server:
  port: 9001

test:
  name: zxf

spring:
  profiles:
    active: pt


---
spring:
  config:
    activate:
      on-profile: pt # 平台线程
  threads:
    virtual:
      enabled: false # 启用虚拟线程。默认值是 false

test:
  name: pt-0000


---
spring:
  config:
    activate:
      on-profile: vt # 虚拟线程
  threads:
    virtual:
      enabled: true # 启用虚拟线程。默认值是 false

test:
  name: vt-2222
