server:
  port: 20000

spring:
  application:
    name: mcp-streamable-webmvc-server
  ai:
    mcp:
      server:
        name: streamable-mcp-server
        protocol: streamable # SSE、STREAMABLE、STATELESS
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "该响应式服务器提供时间信息工具和资源"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        request-timeout: 20s
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
          disallow-delete: false

management:
  endpoints:
    web:
      exposure:
        include: "*" # 开启全部。但没有 ai-tools 端点

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
        server: DEBUG
