spring:
  application:
    name: gateway-sentinel-control
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - StripPrefix=1

---
# 端口 1 环境
spring:
  config:
    activate:
      on-profile: port1
server:
  port: 9641


---
# 端口 2 环境
spring:
  config:
    activate:
      on-profile: port2
server:
  port: 9642