server:
  port: 9001

test:
  name: zxf

spring:
  profiles:
    #active: dev
    active: test

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    ROOT: info

test:
  name: dev-0000